title: Studio Nari
email: studio@studionari.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  NARI is a creative consultancy and branding studio, founded by the award winning Caterina Bianchini, established to bridge the gap between design and art.
baseurl: ""
url: "https://www.studionari.co.uk" 
instagram_username: studionari
permalink: pretty

# Build settings
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-loading-lazy
  # Currently NOT working - jekyll-autoprefixer
sass:
  style: compressed
collections:
  projects:
    output: true
  clients:
    output: true
  sectors:
    output: true
  services:
    output: true
  years:
    output: true