backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
site_url: https://studionari.netlify.app
logo_url: https://studionari.netlify.app/assets/images/logo.svg
display_url: https://studionari.com
local_backend:
  # when using a custom proxy server port
  url: http://localhost:4000/
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']
publish_mode: editorial_workflow
collections:
  - label: "Main Pages"
    label_singular: "Page"
    name: "pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "index.markdown"
        editor:
          preview: false
        fields:
          - {label: Page Name, name: title, widget: string, default: "Home"}
          - {label: SEO Page Description, name: seo-description, widget: string, required: false}
          - label: Homepage Introduction Feature
            name: intro
            widget: object
            collapsed: false
            summary: Use this for the mouse movement homepage feature
            fields:
              - {label: Turn the introduction on or off?, name: toggle, widget: boolean, default: true}
              - {label: Text for introduction hover, name: text, widget: string, default: "Click to enter"}
              - label: Introduction Images and Videos
                label_singular: Item
                name: content
                widget: list
                min: 5
                max: 5
                hint: Use this to change the images or videos that display in the introduction item - only use the default switch on ONE item
                types:
                  - label: "Image"
                    name: "introimage"
                    widget: "object"
                    fields:
                      - {label: 'Do you want this to be the default item?', name: toggle, widget: boolean}
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Short Description", name: "desc", widget: "string", required: false}
                  - label: "Video"
                    name: "introvideo"
                    widget: "object"
                    fields:
                      - {label: 'Do you want this to be the default item?', name: toggle, widget: boolean}
                      - { label: "Video", name: "video", widget: "file" }
                      - { label: "Short Description", name: "desc", widget: "string", required: false}
          - label: Homepage Text Fields
            name: text
            widget: object
            collapsed: false
            hint: Use this to change some of the text elements that are only on the Homepage
            fields:
              - {label: Filters Title, name: filters, widget: string, default: "Filters"}
              - {label: Full View Title, name: full, widget: string, default: "Full View"}
              - {label: List View Title, name: list, widget: string, default: "List View"}
              - {label: Grid View Title, name: grid, widget: string, default: "Grid View"}
              - {label: Project Title, name: project, widget: string, default: "Project"}
              - {label: Description Title, name: description, widget: string, default: "Description"}
              - {label: Client Title, name: client, widget: string, default: "Client"}
              - {label: Year Title, name: year, widget: string, default: "Year"}
              - {label: Services Title, name: service, widget: string, default: "Year"}
      - label: "About"
        name: "about"
        file: "about.markdown"
        editor:
          preview: false
        fields:
          - {label: Page Name, name: title, widget: string, default: "About"}
          - {label: SEO Page Description, name: seo-description, widget: string, required: false}
          - label: About Sections
            label_singular: Section
            name: aboutBuilder
            widget: list
            hint: Add sections to the About page
            summary: '{{fields.title}}'
            fields:
              - { label: "Section Title", name: "title", widget: "string"}
              - label: "Section Body"
                name: "body"
                widget: "markdown"
                modes: ['rich_text']
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    identifier_field: '{{fields.title}}'
    folder: "_projects/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Layout, name: layout, widget: hidden, default: project}
      - {label: Footer, name: footer, widget: hidden, default: project}
      - {label: Project Title, name: title, widget: string}
      - { label: "Featured Image", name: "featuredImage", widget: "image", hint: This is the image that is used on the project page - these should all be the same ratio and size using a template }
      - {label: Short Decsription, name: desc, widget: string, hint: Keep this to a maximum of 80 characters including spaces}
      # Insert the relation to Client, Sector, Services and Years here
      - label: "Client"
        name: "client"
        widget: "relation"
        collection: "clients"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: title
        required: false
        multiple: false
      - label: "Sectors"
        name: "sectors"
        widget: "relation"
        collection: "sectors"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: title
        required: false
        multiple: true
      - label: "Services"
        name: "services"
        widget: "relation"
        collection: "services"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: title
        required: false
        multiple: true
      - label: "Year"
        name: "year"
        widget: "relation"
        collection: "years"
        search_fields: ["year"]
        display_fields: ["year"]
        value_field: year
        required: false
        multiple: false
      - label: Project Content
        label_singular: Content
        name: projectBuilder
        widget: list
        types:
          - label: "Image"
            name: "_section_image"
            widget: "object"
            summary: "{{fields.meaningful}}"
            fields:
              - { label: "Meaningful Name", name: "meaningful", widget: "string", hint: This will make organising the content easier}
              - label: Size
                name: size
                widget: select
                options:
                  - { label: "Fit to space", value: "fit" }
                  - { label: "Fill all the space", value: "fill" }
                default: fit
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "desc", widget: "string", required: false}
          - label: "Video"
            name: "_section_video"
            widget: "object"
            summary: "{{fields.meaningful}}"
            fields:
              - { label: "Meaningful Name", name: "meaningful", widget: "string", hint: This will make organising the content easier}
              - label: Size
                name: size
                widget: select
                options:
                  - { label: "Fit to space", value: "fit" }
                  - { label: "Fill all the space", value: "fill" }
                default: fit
              - { label: "Video", name: "video", widget: "file" }
              - { label: "Does the video need sound?", name: "sound", widget: "boolean", required: false }
              - { label: "Description", name: "desc", widget: "string", required: false}
          - label: "Duo Image"
            name: "_section_duo"
            widget: "object"
            summary: "{{fields.meaningful}}"
            fields:
              - { label: "Meaningful Name", name: "meaningful", widget: "string", hint: This will make organising the content easier}
              - { label: "Image One", name: "image", widget: "image" }
              - { label: "Image Two", name: "imageTwo", widget: "image" }
              - { label: "Description", name: "desc", widget: "string", required: false}
          - label: "Text"
            name: "_section_text"
            widget: "object"
            summary: "{{fields.meaningful}}"
            fields:
              - { label: "Meaningful Name", name: "meaningful", widget: "string", hint: This will make organising the content easier}
              - label: Columns
                name: size
                widget: select
                options:
                  - { label: "One Column", value: "one" }
                  - { label: "Two Columns", value: "two" }
                default: one
              - { label: "Text One", name: "textOne", widget: "markdown", modes: ['rich_text'], hint: This will be the first column if you select Two Columns }
              - { label: "Text Two", name: "textTwo", widget: "markdown", modes: ['rich_text'], hint: This will be the second column if you select Two Columns but leave blank if only using One Column, required: false}
  - name: pages
    label: "Secondary Pages"
    label_singular: "Page"
    identifier_field: '{{fields.title}}'
    folder: "_pages/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Page Name, name: title, widget: string, default: "Home"}
      - {label: SEO Page Description, name: seo-description, widget: string, required: false}
      - { label: "Page Content", name: body, widget: "markdown", modes: ['rich_text'] }
  - name: clients
    label: "Project Clients"
    label_singular: "Client"
    identifier_field: '{{fields.title}}'
    folder: "_clients/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Client Name, name: title, widget: string}
  - name: sectors
    label: "Project Sectors"
    label_singular: "Sector"
    identifier_field: '{{fields.title}}'
    folder: "_sectors/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Sector Title, name: title, widget: string}
  - name: services
    label: "Project Services"
    label_singular: "Service"
    identifier_field: '{{fields.title}}'
    folder: "_services/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Service Title, name: title, widget: string}
  - name: years
    label: "Project Years"
    label_singular: "Year"
    identifier_field: '{{fields.year}}'
    folder: "_years/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Year, name: year, widget: number, default: 2021, value_type: int, min: 2000, max: 2040, step: 1}
  - name: news
    label: "News"
    label_singular: "News Item"
    identifier_field: '{{fields.title}}'
    folder: "_news/"
    create: true
    editor:
      preview: false
    fields:
      - {label: Link URL, name: linkURL, widget: string}
      - {label: Heading, name: title, widget: string}
      - {label: Body, name: body, widget: markdown, modes: ['rich_text']}
      - {label: "Optional image", name: "image", widget: "image", hint: Leaving this blank will mean a larger title, required: false}
      - {label: Publish Date, name: date, widget: datetime, date_format: true, time_format: false}
  - name: 'config'
    label: 'Site Settings'
    editor:
      preview: false
    files:
      - label: 'Site Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        summary: 'For the main navigation at the top of the page'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            max: 7
            min: 1
            summary: '{{fields.name}}'
            fields:
              - { label: Name, name: name, widget: string }
              - label: Link
                name: link
                widget: string
                default: /
      - label: 'Contact Drawer'
        name: 'contact'
        file: '_data/contact.yml'
        summary: 'For the main navigation at the top of the page'
        fields:
          - { label: Content, name: body, widget: markdown }
      - label: 'Cookie Banner'
        name: 'cookie'
        file: '_data/cookie.yml'
        fields:
          - {label: Cookie Banner Main Text, name: body, widget: string, default: 'We use cookies to improve your browsing experience.'}
          - {label: Cookie Banner Button Text, name: btn, widget: string, default: 'Learn More'}